---
title: "revealjs learnr"
output: 
  revealjs::revealjs_presentation:
    theme: "simple"
    center: false
runtime: shiny_prerendered
description: >
  This is a demo of a learnr tutorial in revealjs format
---

```{css, echo = FALSE}
.reveal .slides {
  text-align: left;
}
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(learnr)
```

## Question 1

```{r letter-a, echo=FALSE}
question("What number is the letter A in the English alphabet? Adding a lot of words here to test out spacing and other things on the slide",
  answer("8"),
  answer("14"),
  answer("1", correct = TRUE),
  answer("23")
)
```

## Question 2

```{r where-am-i, echo=FALSE}
question("Where are you right now? (select ALL that apply)",
  answer("Planet Earth", correct = TRUE),
  answer("Pluto"),
  answer("At a computing device", correct = TRUE),
  answer("In the Milky Way", correct = TRUE),
  incorrect = "Incorrect. You're on Earth, in the Milky Way, at a computer."
)
```

## Another Slide

This is content with bullets. Adding a lot of words here to test out spacing and other things on the slide

* item 1
* item 2
* item 3
